version: '3.6'

services:
  db:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
        - db-data:/var/lib/postgresql/data
        - db-logs:/var/log/postgresql
    networks:
      - app-network

volumes:
  db-data:
  db-logs:

networks:
  app-network:
    driver: bridge
