const DEFAULT_API_PORT = 4000;
const PARSE_INT_RADIX_10 = 10;
const DEFAULT_ENV_FILES = ['.env', '.env.example'];
const ENV_API_PORT_KEY = 'PORT';
const CONFIG_PORT_KEY = 'port';
const ENV_USE_INITIAL_DATA = 'USE_INITIAL_MOCK_DATA';
const ENV_LOG_MAX_FILE_SIZE_KEY = 'LOG_MAX_FILE_SIZE';
const DEFAULT_LOG_MAX_FILE_SIZE = 1024;
const ENV_LOG_LEVELS_KEY = 'LOG_LEVELS';
const DEFAULT_LOG_LEVELS = 'log,error,warn,debug,verbose';
const CONFIG_LOG_LEVELS_KEY = 'logLevels';

export {
  DEFAULT_API_PORT,
  PARSE_INT_RADIX_10,
  DEFAULT_ENV_FILES,
  ENV_API_PORT_KEY,
  CONFIG_PORT_KEY,
  ENV_USE_INITIAL_DATA,
  ENV_LOG_MAX_FILE_SIZE_KEY,
  DEFAULT_LOG_MAX_FILE_SIZE,
  ENV_LOG_LEVELS_KEY,
  DEFAULT_LOG_LEVELS,
  CONFIG_LOG_LEVELS_KEY,
};
