const DEFAULT_API_PORT = 4000;
const PARSE_INT_RADIX_10 = 10;
const DEFAULT_ENV_FILES = ['.env', '.env.example'];
const ENV_API_PORT_KEY = 'PORT';
const CONFIG_PORT_KEY = 'port';

const ENV_USE_INITIAL_DATA = 'USE_INITIAL_MOCK_DATA';
const CONFIG_USE_INITIAL_DATA = 'useInitialData';

export {
  DEFAULT_API_PORT,
  PARSE_INT_RADIX_10,
  DEFAULT_ENV_FILES,
  ENV_API_PORT_KEY,
  CONFIG_PORT_KEY,
  CONFIG_USE_INITIAL_DATA,
  ENV_USE_INITIAL_DATA,
};
