const USER_LOGIN_MIN_LENGTH = 3;
const USER_LOGIN_MAX_LENGTH = 20;
const USER_PASSWORD_MIN_LENGTH = 3;
const USER_PASSWORD_MAX_LENGTH = 20;

const USER_VERSION_INCREMENT = 1;

export {
  USER_LOGIN_MIN_LENGTH,
  USER_LOGIN_MAX_LENGTH,
  USER_PASSWORD_MIN_LENGTH,
  USER_PASSWORD_MAX_LENGTH,
  USER_VERSION_INCREMENT,
};
